// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARiqYH11aseZyx6bItntyQ4l_deGgilCU',
    appId: '1:1054193949485:web:fb3d6015adf1f0d92591a4',
    messagingSenderId: '1054193949485',
    projectId: 'testecommerce-619dd',
    authDomain: 'testecommerce-619dd.firebaseapp.com',
    storageBucket: 'testecommerce-619dd.appspot.com',
    measurementId: 'G-0JP21S1JXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXdVHzHSsCXzEfn9Ifatj75MxB-x1SRg',
    appId: '1:1054193949485:android:6406e9b98c8c05002591a4',
    messagingSenderId: '1054193949485',
    projectId: 'testecommerce-619dd',
    storageBucket: 'testecommerce-619dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9sLLJ63G1CCPEGBy8kStaVcC-mIlaBTw',
    appId: '1:1054193949485:ios:d22b674aa927e6eb2591a4',
    messagingSenderId: '1054193949485',
    projectId: 'testecommerce-619dd',
    storageBucket: 'testecommerce-619dd.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9sLLJ63G1CCPEGBy8kStaVcC-mIlaBTw',
    appId: '1:1054193949485:ios:d22b674aa927e6eb2591a4',
    messagingSenderId: '1054193949485',
    projectId: 'testecommerce-619dd',
    storageBucket: 'testecommerce-619dd.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARiqYH11aseZyx6bItntyQ4l_deGgilCU',
    appId: '1:1054193949485:web:01b29c53adaf4b692591a4',
    messagingSenderId: '1054193949485',
    projectId: 'testecommerce-619dd',
    authDomain: 'testecommerce-619dd.firebaseapp.com',
    storageBucket: 'testecommerce-619dd.appspot.com',
    measurementId: 'G-2VL9E23PMK',
  );
}
